name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: sudo make
    - name: makeC
      run: cd code && sudo make  
    - name: makeC check
      run: cd code && sudo make check  
    - name: makeC distcheck
      run: cd code && sudo make distcheck 
